name: Run AutoDocstring

on:
  push:
    branches:
      - master
      
permissions:
  contents: write  # Allows pushing changes

jobs:
  auto_document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Fetch Changed Files
        id: changed-files
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          else
            CHANGED_FILES=$(git ls-files)
          fi
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Convert newline-separated file list to space-separated without extra quotes
          echo "files<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Auto Docstring
        uses: SydFloyd/AutoDocumenter@master
        with:
          files: ${{ env.files }}
          secret: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git status  # Debugging: Show changed files
          git diff --staged  # Debugging: Show what would be committed
          git diff --cached --quiet || git commit -m "Generated Docstrings"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
